### ISSUE TITLE
setup.py install does not include _vendored

### ISSUE THREAD

**Issue by zackmdavis** [alexbecker/dotlock#1]
I installed dotlock by running `sudo python3.6 setup.py install`. ([I know this is bad](https://stackoverflow.com/questions/21055859/what-are-the-risks-of-running-sudo-pip), but I think it's defensible if I trust the author of dotlock to not secretly write malware and I'm not jeopardizing system stability since this Python 3.6 from a PPA is not the main system Python. Also, [YOLO](https://www.youtube.com/watch?v=b8TQccgqX2Y).) But when I try to run it, I get:

```
zmd@ReflectiveCoherence:~/Code/Finetooth$ dotlock init
Traceback (most recent call last):
  File "/usr/local/bin/dotlock", line 9, in <module>
    load_entry_point('dotlock==0.2.0', 'console_scripts', 'dotlock')()
  File "/usr/local/lib/python3.6/dist-packages/setuptools-39.1.0-py3.6.egg/pkg_resources/__init__.py", line 480, in load_entry_point
  File "/usr/local/lib/python3.6/dist-packages/setuptools-39.1.0-py3.6.egg/pkg_resources/__init__.py", line 2691, in load_entry_point
  File "/usr/local/lib/python3.6/dist-packages/setuptools-39.1.0-py3.6.egg/pkg_resources/__init__.py", line 2322, in load
  File "/usr/local/lib/python3.6/dist-packages/setuptools-39.1.0-py3.6.egg/pkg_resources/__init__.py", line 2328, in resolve
  File "/usr/local/lib/python3.6/dist-packages/dotlock-0.2.0-py3.6.egg/dotlock/__main__.py", line 7, in <module>
    from dotlock.graph import graph_resolution
  File "/usr/local/lib/python3.6/dist-packages/dotlock-0.2.0-py3.6.egg/dotlock/graph.py", line 3, in <module>
    from dotlock.resolve import Requirement
  File "/usr/local/lib/python3.6/dist-packages/dotlock-0.2.0-py3.6.egg/dotlock/resolve.py", line 10, in <module>
    from dotlock.caching import connect_to_cache
  File "/usr/local/lib/python3.6/dist-packages/dotlock-0.2.0-py3.6.egg/dotlock/caching.py", line 9, in <module>
    from dotlock.dist_info_parsing import RequirementInfo, CandidateInfo, PackageType
  File "/usr/local/lib/python3.6/dist-packages/dotlock-0.2.0-py3.6.egg/dotlock/dist_info_parsing.py", line 16, in <module>
    from dotlock._vendored.pep425tags import get_supported
ModuleNotFoundError: No module named 'dotlock._vendored'
```

**Comment by alexbecker** [comment]
Fixed, thanks!

(Testing with `tox` now, so this *should* not happen again.)
